# Do a clean install of node dependencies and run tests across different versions of node

name: Test & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run at 04:26 UTC on 9th of every month
    - cron: '26 4 9 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12', '14', '16']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
